services:
  - type: web
    name: voicebot-ua
    runtime: python
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y $(cat apt-packages)
      pip install -r requirements.txt
    startCommand: python start.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.0 